[package]
name = "kclvm-cmd"
version = "0.4.6"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "3.2.22"
compiler_base_session = {path = "../../compiler_base/session"}

kclvm-capi = {path = "../capi",version = "0.4.6"}
kclvm-parser = {path = "../parser"}
kclvm-runner = {path = "../runner"}
kclvm-config = {path = "../config"}
kclvm-runtime = {path = "../runtime"}
kclvm-tools = {path = "../tools"}
kclvm-error = {path = "../error"}
