[package]
name = "compiler-base-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
compiler-base-style = {path="../style", version="0.1.0"}
compiler-base-diagnostic = {path = "../diagnostic", version = "0.1.0"}
synstructure = "0.12.1"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"
quote = "1"
