[package]
name = "compiler_base_session"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_base_span = "0.1.0"
compiler_base_error = "0.1.0"
anyhow = "1.0"
