[package]
name = "kclvm-utils"
version = "0.8.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[target.'cfg(windows)'.dependencies]
fslock = "0.2.1"

[target.'cfg(unix)'.dependencies]
fslock = "0.2.1"
