[package]
name = "kclvm-span"
version = "0.4.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_span = { path = "../3rdparty/rustc_span" }

kclvm-macros = { path = "../macros" }
scoped-tls = "1.0"