[package]
name = "kclvm-ast-pretty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kclvm-parser = {path = "../parser", version = "0.1.0"}
kclvm-error = {path = "../error", version = "0.1.0"}
kclvm-ast = {path = "../ast", version = "0.1.0"}
indexmap = "1.0"
<<<<<<< HEAD
<<<<<<< HEAD
fancy-regex = "0.7.1"
<<<<<<< HEAD
pretty_assertions = "1.3.0"
=======
fancy-regex = "0.7.1"
>>>>>>> b15d822 (mv query to ast_pretty)
=======
fancy-regex = "0.7.1"
>>>>>>> f9e4f7b (remove useless dependencies)
=======
pretty_assertions = "1.3.0"
>>>>>>> 925e86b (add pretty_assertions)
