[package]
name = "kclvm-driver"
version = "0.4.6"
edition = "2021"

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kclvm-config ={ path = "../config"}
kclvm-runtime ={ path = "../runtime"}
kclvm-utils ={ path = "../utils"}
kclvm-parser ={ path = "../parser"}
kclvm-ast ={ path = "../ast"}
