[package]
name = "compiler_base_error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_base_span = {path = "../span", version = "0.1.0"}
compiler_base_macros = {path = "../macros", version = "0.1.0"}
rustc_errors = {path="../3rdparty/rustc_errors", version="0.1.0"}
unic-langid = {version="0.9.0", features = ["macros"]}

fluent = "0.16.0"
termcolor = "1.0"
walkdir = "2"
anyhow = "1.0"