[package]
name = "compiler-base-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler-base = {path="../", version = "0.1.0"}
compiler-base-diagnostic = {path = "../diagnostic", version = "0.1.0"}
compiler-base-macros = {path = "../macros", version = "0.1.0"}
